import '../constants/app_constants.dart';
import 'module_definition.dart';

/// IVE-COMMERCIAL-RELEASE-CONTROL-PLANE-01 — inventário autoritativo de
/// módulos, construído por auditoria de repositório (não por suposição).
/// Cobertura: lib/app.dart (tabela de rotas GoRouter), lib/shared/widgets/
/// app_drawer.dart (navegação atual), cada tela/serviço referenciado.
///
/// COMMERCIAL V1 (seção 04 da missão) é uma lista curada e explícita do
/// owner/architect -- não é "tudo que já funciona". Vários módulos abaixo
/// estão tecnicamente completos e funcionando (ACTIVE) mas com
/// `commercialEnabled: false` porque não fazem parte do lançamento V1
/// definido pela missão. Isso é uma decisão de produto já tomada no texto
/// da missão, não uma decisão desta implementação -- reportado
/// explicitamente no relatório final, não escondido.
///
/// NÃO REMOVA módulos desta lista (regra explícita da missão) -- só ajuste
/// status/commercialEnabled conforme a realidade evoluir.
const List<ModuleDefinition> kModuleRegistry = [
  ModuleDefinition(
    moduleId: 'command-center',
    namePt: 'OS Command Center',
    nameEn: 'OS Command Center',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeHome,
    backendDependencies: ['projects', 'ecosystem intelligence', 'action queue', 'opportunity lab', 'knowledge graph'],
    databaseDependencies: ['projects', 'action_queue', 'opportunity_lab', 'knowledge_items'],
    readinessPt: 'Totalmente funcional -- agrega dados já existentes de outros módulos.',
    readinessEn: 'Fully functional -- aggregates data already produced by other modules.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'business-dashboard',
    namePt: 'Business Dashboard',
    nameEn: 'Business Dashboard',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeDashboard,
    readinessPt: 'Funcional. Sobreposição parcial de propósito com o Command Center -- não unificados nesta missão (decisão de produto, não técnica).',
    readinessEn: 'Functional. Partial purpose overlap with Command Center -- not unified in this mission (product decision, not technical).',
    releaseClassification: ModuleReleaseClass.commercialV1,
    notes: 'Ver Command Center -- possível redundância a avaliar pelo owner em uma missão futura.',
  ),
  ModuleDefinition(
    moduleId: 'projects',
    namePt: 'Projetos',
    nameEn: 'Projects',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeProjects,
    databaseDependencies: ['projects'],
    readinessPt: 'Totalmente funcional.',
    readinessEn: 'Fully functional.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'knowledge-vault',
    namePt: 'Cofre de Conhecimento',
    nameEn: 'Knowledge Vault',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeKnowledge,
    edgeFunctions: ['extract-knowledge', 'process-file'],
    databaseDependencies: ['knowledge_items', 'knowledge_analysis'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional. Inclui import local (PDF/DOCX/TXT) e Google Drive. RLS e isolamento entre usuários verificados ao vivo em produção em missão anterior.',
    readinessEn: 'Fully functional. Includes local import (PDF/DOCX/TXT) and Google Drive. RLS and cross-user isolation verified live in production in a prior mission.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'strategy-generation',
    namePt: 'Geração de Estratégia',
    nameEn: 'Strategy Generation',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeKnowledgeStrategy,
    edgeFunctions: ['generate-strategy'],
    databaseDependencies: ['knowledge_strategies'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional -- sub-fluxo do Cofre de Conhecimento (por item, não um catálogo próprio).',
    readinessEn: 'Fully functional -- a sub-flow of Knowledge Vault (per-item, not a standalone catalog entry).',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'website-analyzer',
    namePt: 'Website Analyzer',
    nameEn: 'Website Analyzer',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeWebsiteAnalyzer,
    edgeFunctions: ['analyze-website'],
    databaseDependencies: ['website_analyses'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional.',
    readinessEn: 'Fully functional.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'market-intelligence',
    namePt: 'Market Intelligence',
    nameEn: 'Market Intelligence',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligence,
    edgeFunctions: ['market-analysis', 'competitor-discovery', 'gap-analysis', 'niche-discovery', 'opportunity-discovery', 'content-cluster', 'revenue-planner'],
    aiDependency: true,
    readinessPt: 'Hub totalmente funcional, com 6 sub-módulos (abaixo) cada um com sua própria Edge Function auditada.',
    readinessEn: 'Fully functional hub, with 6 sub-modules (below) each backed by its own audited Edge Function.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'competitor-discovery',
    namePt: 'Descoberta de Concorrentes',
    nameEn: 'Competitor Discovery',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceCompetitors,
    edgeFunctions: ['competitor-discovery'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'gap-analysis',
    namePt: 'Análise de Lacunas',
    nameEn: 'Gap Analysis',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceGaps,
    edgeFunctions: ['gap-analysis'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'niche-discovery',
    namePt: 'Descoberta de Nichos',
    nameEn: 'Niche Discovery',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceNiches,
    edgeFunctions: ['niche-discovery'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'opportunity-discovery',
    namePt: 'Descoberta de Oportunidades',
    nameEn: 'Opportunity Discovery',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceOpportunities,
    edgeFunctions: ['opportunity-discovery'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'content-cluster',
    namePt: 'Cluster de Conteúdo',
    nameEn: 'Content Cluster',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceCluster,
    edgeFunctions: ['content-cluster'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'revenue-planner',
    namePt: 'Planejador de Receita',
    nameEn: 'Revenue Planner',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeMarketIntelligenceRevenue,
    edgeFunctions: ['revenue-planner'],
    aiDependency: true,
    readinessPt: 'Funcional -- sub-módulo do Market Intelligence.',
    readinessEn: 'Functional -- Market Intelligence sub-module.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'opportunity-lab',
    namePt: 'Opportunity Lab',
    nameEn: 'Opportunity Lab',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeOpportunityLab,
    databaseDependencies: ['opportunity_lab'],
    readinessPt: 'Totalmente funcional.',
    readinessEn: 'Fully functional.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'action-engine',
    namePt: 'Action Engine',
    nameEn: 'Action Engine',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeActionEngine,
    edgeFunctions: ['generate-project-actions'],
    databaseDependencies: ['action_queue'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional.',
    readinessEn: 'Fully functional.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'context-copilot',
    namePt: 'Context Copilot',
    nameEn: 'Context Copilot',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: null,
    edgeFunctions: ['context-copilot'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional. Por design não é uma rota própria -- é um overlay global (assistente ambiente), renderizado sobre todas as telas.',
    readinessEn: 'Fully functional. By design it is not its own route -- it is a global overlay (ambient assistant), rendered over every screen.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'file-import',
    namePt: 'Importação de Arquivos (PDF/DOCX/TXT)',
    nameEn: 'File Import (PDF/DOCX/TXT)',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: null,
    edgeFunctions: ['process-file'],
    readinessPt: 'Totalmente funcional -- parte do fluxo do Cofre de Conhecimento. Auditado em missão dedicada (auth gate, allowlist de tipo, teto de tamanho, proteção contra zip bomb no DOCX).',
    readinessEn: 'Fully functional -- part of the Knowledge Vault flow. Audited in a dedicated mission (auth gate, type allowlist, size ceiling, DOCX zip-bomb protection).',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'google-drive-import',
    namePt: 'Importação via Google Drive',
    nameEn: 'Google Drive Import',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: null,
    edgeFunctions: ['process-file'],
    readinessPt: 'Totalmente funcional -- parte do fluxo do Cofre de Conhecimento. Escopo OAuth (drive.readonly) mais amplo que o necessário -- ver nota. Google Docs nativos exportados com segurança antes do parsing.',
    readinessEn: 'Fully functional -- part of the Knowledge Vault flow. OAuth scope (drive.readonly) is broader than needed -- see note. Native Google Docs are safely exported before parsing.',
    releaseClassification: ModuleReleaseClass.commercialV1,
    notes: 'DRIVE SCOPE: OVERBROAD / POST-MVP HARDENING (não bloqueia lançamento comercial -- ver relatório de missão anterior).',
  ),
  ModuleDefinition(
    moduleId: 'usage-quota',
    namePt: 'Uso / Cota',
    nameEn: 'Usage / Quota',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: null,
    databaseDependencies: ['ai_usage', 'profiles'],
    readinessPt: 'Totalmente funcional -- reserva/estorno de cota via RPC server-side (try_reserve_ai_quota/refund_ai_quota), auditado e testado.',
    readinessEn: 'Fully functional -- server-side quota reserve/refund via RPC, audited and tested.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),
  ModuleDefinition(
    moduleId: 'plans-upgrade',
    namePt: 'Planos / Upgrade',
    nameEn: 'Plans / Upgrade',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeUpgrade,
    edgeFunctions: ['create-checkout-session', 'stripe-webhook'],
    databaseDependencies: ['subscriptions', 'processed_webhook_events'],
    readinessPt: 'Checkout Stripe real (TEST MODE) implementado e implantado. Prova de ciclo de vida real ainda pendente das credenciais de teste do owner.',
    readinessEn: 'Real Stripe checkout (TEST MODE) implemented and deployed. Real lifecycle proof still pending the owner\'s test credentials.',
    releaseClassification: ModuleReleaseClass.commercialV1,
  ),

  // ── Fora do catálogo comercial V1 (funcionais, mas não no lançamento) ──
  ModuleDefinition(
    moduleId: 'improve-post',
    namePt: 'Melhorar Post',
    nameEn: 'Improve Post',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeGenerate,
    edgeFunctions: ['improve-post'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional, mas fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, but outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
  ),
  ModuleDefinition(
    moduleId: 'personas',
    namePt: 'Personas / Marcas',
    nameEn: 'Personas / Brands',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.pro,
    route: AppConstants.routePersonas,
    databaseDependencies: ['personas'],
    readinessPt: 'Totalmente funcional, hoje já trancado por plano Pro no drawer. Fora da lista V1 explícita da missão -- passa a não aparecer nem para usuários Pro até uma decisão futura do owner.',
    readinessEn: 'Fully functional, already Pro-gated in the drawer today. Outside the mission\'s explicit V1 list -- now hidden even from Pro users pending a future owner decision.',
    releaseClassification: ModuleReleaseClass.postV1,
    notes: 'MUDANÇA DE COMPORTAMENTO: usuários Pro que hoje veem este item deixam de vê-lo. Sinalizado explicitamente no relatório final.',
  ),
  ModuleDefinition(
    moduleId: 'content-library',
    namePt: 'Biblioteca',
    nameEn: 'Content Library',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.pro,
    route: AppConstants.routeContent,
    databaseDependencies: ['content_items'],
    readinessPt: 'Totalmente funcional, hoje já trancado por plano Pro. Fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, already Pro-gated today. Outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
    notes: 'MUDANÇA DE COMPORTAMENTO: usuários Pro que hoje veem este item deixam de vê-lo. Sinalizado explicitamente no relatório final.',
  ),
  ModuleDefinition(
    moduleId: 'calendar',
    namePt: 'Calendário Editorial',
    nameEn: 'Editorial Calendar',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.pro,
    route: AppConstants.routeCalendar,
    readinessPt: 'Totalmente funcional, hoje já trancado por plano Pro. Fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, already Pro-gated today. Outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
    notes: 'MUDANÇA DE COMPORTAMENTO: usuários Pro que hoje veem este item deixam de vê-lo. Sinalizado explicitamente no relatório final.',
  ),
  ModuleDefinition(
    moduleId: 'campaigns',
    namePt: 'Campanhas',
    nameEn: 'Campaigns',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeCampaigns,
    edgeFunctions: ['generate-campaign'],
    databaseDependencies: ['campaigns'],
    aiDependency: true,
    readinessPt: 'Totalmente funcional, mas fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, but outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
  ),
  ModuleDefinition(
    moduleId: 'performance',
    namePt: 'Performance',
    nameEn: 'Performance',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routePerformance,
    databaseDependencies: ['performance_metrics'],
    readinessPt: 'Totalmente funcional, mas fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, but outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
  ),
  ModuleDefinition(
    moduleId: 'roi-tracker',
    namePt: 'ROI Tracker',
    nameEn: 'ROI Tracker',
    status: ModuleStatus.active,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeRoiTracker,
    databaseDependencies: ['roi_metrics'],
    readinessPt: 'Totalmente funcional, mas fora da lista V1 explícita da missão.',
    readinessEn: 'Fully functional, but outside the mission\'s explicit V1 list.',
    releaseClassification: ModuleReleaseClass.postV1,
  ),
  ModuleDefinition(
    moduleId: 'executive-dashboard',
    namePt: 'Executive Dashboard',
    nameEn: 'Executive Dashboard',
    status: ModuleStatus.beta,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeExecutiveDashboard,
    readinessPt: 'Funcional, mas é uma camada de agregação client-side (sem Edge Function/tabela própria) sobre dados de outros módulos -- tratado como Beta, não V1.',
    readinessEn: 'Functional, but a client-side aggregation layer (no dedicated Edge Function/table) over other modules\' data -- treated as Beta, not V1.',
    releaseClassification: ModuleReleaseClass.betaProgram,
  ),
  ModuleDefinition(
    moduleId: 'decision-center',
    namePt: 'Decision Center',
    nameEn: 'Decision Center',
    status: ModuleStatus.beta,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeEcosystem,
    readinessPt: 'Mesmo padrão do Executive Dashboard -- agregação client-side, tratado como Beta.',
    readinessEn: 'Same pattern as Executive Dashboard -- client-side aggregation, treated as Beta.',
    releaseClassification: ModuleReleaseClass.betaProgram,
  ),
  ModuleDefinition(
    moduleId: 'resource-allocation',
    namePt: 'Alocação de Recursos',
    nameEn: 'Resource Allocation',
    status: ModuleStatus.beta,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeEcosystemResources,
    readinessPt: 'Mesmo padrão -- agregação client-side, tratado como Beta.',
    readinessEn: 'Same pattern -- client-side aggregation, treated as Beta.',
    releaseClassification: ModuleReleaseClass.betaProgram,
  ),
  ModuleDefinition(
    moduleId: 'weekly-briefing',
    namePt: 'Briefing Semanal',
    nameEn: 'Weekly Briefing',
    status: ModuleStatus.beta,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeEcosystemBriefing,
    readinessPt: 'Mesmo padrão -- agregação client-side, tratado como Beta.',
    readinessEn: 'Same pattern -- client-side aggregation, treated as Beta.',
    releaseClassification: ModuleReleaseClass.betaProgram,
  ),
  ModuleDefinition(
    moduleId: 'advisor-onboarding',
    namePt: 'Onboarding do Consultor',
    nameEn: 'Advisor Onboarding',
    status: ModuleStatus.inDevelopment,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.free,
    route: AppConstants.routeAdvisorOnboarding,
    readinessPt: 'Órfã -- rota existe mas nenhum ponto de entrada de navegação foi encontrado em nenhuma tela. Só alcançável por URL direta.',
    readinessEn: 'Orphaned -- the route exists but no navigation entry point was found in any screen. Reachable only via direct URL.',
    releaseClassification: ModuleReleaseClass.internalTooling,
  ),
  ModuleDefinition(
    moduleId: 'decision-simulator',
    namePt: 'Simulador de Decisão',
    nameEn: 'Decision Simulator',
    status: ModuleStatus.inDevelopment,
    adminVisible: true,
    adminClickable: false,
    commercialEnabled: false,
    minimumPlan: ModulePlan.admin,
    route: null,
    edgeFunctions: ['decision-simulator'],
    aiDependency: true,
    readinessPt: 'Backend completo (Edge Function auditada e testada), mas sem nenhuma tela consumidora -- nenhuma rota, nenhum ponto de entrada na UI.',
    readinessEn: 'Backend complete (audited and tested Edge Function), but no consuming screen exists -- no route, no UI entry point.',
    releaseClassification: ModuleReleaseClass.internalTooling,
    notes: 'adminClickable=false: não há para onde navegar ainda.',
  ),
  ModuleDefinition(
    moduleId: 'intelligence-debug',
    namePt: 'Intelligence Debug',
    nameEn: 'Intelligence Debug',
    status: ModuleStatus.internal,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.admin,
    route: AppConstants.routeIntelligenceDebug,
    readinessPt: 'Ferramenta interna de observabilidade/auditoria. Corrigido nesta missão: não tinha nenhum gate de admin (nem visual, nem de rota) apesar de expor dados de score de todos os projetos -- agora exige role admin.',
    readinessEn: 'Internal observability/audit tool. Fixed in this mission: had no admin gate at all (neither visual nor route-level) despite exposing score data for every project -- now requires the admin role.',
    releaseClassification: ModuleReleaseClass.internalTooling,
    notes: 'ACHADO DE SEGURANÇA CORRIGIDO: qualquer usuário autenticado conseguia acessar via /intelligence-debug antes desta missão.',
  ),
  ModuleDefinition(
    moduleId: 'admin-panel',
    namePt: 'Painel Admin',
    nameEn: 'Admin Panel',
    status: ModuleStatus.internal,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: false,
    minimumPlan: ModulePlan.admin,
    route: AppConstants.routeAdmin,
    databaseDependencies: ['profiles'],
    readinessPt: 'Totalmente funcional. Autorização real via RLS (admin_all_profiles) + gatilho de proteção contra auto-promoção -- verificado ao vivo, sem regressão.',
    readinessEn: 'Fully functional. Real authorization via RLS (admin_all_profiles) + self-promotion protection trigger -- verified live, no regression.',
    releaseClassification: ModuleReleaseClass.internalTooling,
  ),
  ModuleDefinition(
    moduleId: 'ive-avatar',
    namePt: 'IVE Avatar',
    nameEn: 'IVE Avatar',
    status: ModuleStatus.beta,
    adminVisible: true,
    adminClickable: true,
    commercialEnabled: true,
    minimumPlan: ModulePlan.free,
    route: null,
    readinessPt: 'Overlay visual global (Rive), em desenvolvimento ativo por workstream paralelo a esta missão -- não auditado em profundidade aqui.',
    readinessEn: 'Global visual overlay (Rive), under active development by a workstream parallel to this mission -- not deeply audited here.',
    releaseClassification: ModuleReleaseClass.betaProgram,
    notes: 'Desenvolvimento paralelo (branches claude/ive-avatar-*) -- fora do escopo de auditoria profunda desta missão.',
  ),
  ModuleDefinition(
    moduleId: 'ive-quant',
    namePt: 'IVE Quant',
    nameEn: 'IVE Quant',
    status: ModuleStatus.planned,
    adminVisible: true,
    adminClickable: false,
    commercialEnabled: false,
    minimumPlan: ModulePlan.admin,
    route: null,
    readinessPt: 'NÃO EXISTE neste repositório. Confirmado por busca exaustiva (grep por "quant"/"backtest"/"paper trading"/"live trading"/"broker"/etc. em todo o repositório): zero código, zero rota, zero modelo. A própria documentação de planejamento do produto (docs/showcase/SHOW_00_CAPABILITY_GAP_MATRIX.md) já registra isto como um repositório externo e separado, nunca integrado, classificado internamente como prioridade P3/futura.',
    readinessEn: 'DOES NOT EXIST in this repository. Confirmed by exhaustive search (grep for "quant"/"backtest"/"paper trading"/"live trading"/"broker"/etc. across the whole repo): zero code, zero route, zero model. The product\'s own planning documentation (docs/showcase/SHOW_00_CAPABILITY_GAP_MATRIX.md) already records this as a separate, external, never-integrated repository, internally classified as P3/future priority.',
    releaseClassification: ModuleReleaseClass.externalPlanned,
    notes: 'QUANT_STATUS: NOT_IMPLEMENTED. QUANT_COMMERCIAL_RECOMMENDATION: SEPARATE_PRODUCT. adminClickable=false: não há nada para abrir. Nenhuma execução financeira ao vivo existe ou foi ativada -- não há o que "ativar" (não existe código).',
  ),
];
