/**
 * Market calendar + calendar-aware freshness tests — IV-QUANT-DATA-PLANE-AND-API-02.
 * Holiday expectations are the exchanges' published schedules (NYSE / LSE),
 * written out by hand below — not generated by the code under test.
 *
 * Execução:
 *   deno test supabase/functions/_shared/quant/calendar_test.ts
 */
import { assert, assertEquals } from 'https://deno.land/std@0.168.0/testing/asserts.ts';
import { addDays, calendarForMic, easterSunday, isTradingDay, marketClock, sessionTimes, weekday } from './calendar.ts';
import { assessSessionFreshness } from './session_freshness.ts';
import type { PriceBar } from './timeseries.ts';

const NYSE = calendarForMic('XNYS')!;
const NASDAQ = calendarForMic('XNAS')!;
const LSE = calendarForMic('XLON')!;

function weekdayHolidays(cal: typeof NYSE, year: number): string[] {
  const out: string[] = [];
  for (let d = `${year}-01-01`; d.startsWith(String(year)); d = addDays(d, 1)) {
    const w = weekday(d);
    if (w !== 0 && w !== 6 && isTradingDay(cal, d) === false) out.push(d.slice(5));
  }
  return out;
}

Deno.test('CAL-01 NYSE/Nasdaq holidays match the published schedules (observance rules, Juneteenth, special closures)', () => {
  const expected: Record<number, string[]> = {
    2022: ['01-17', '02-21', '04-15', '05-30', '06-20', '07-04', '09-05', '11-24', '12-26'], // Jan 1 on Saturday: NOT moved to Fri Dec 31
    2024: ['01-01', '01-15', '02-19', '03-29', '05-27', '06-19', '07-04', '09-02', '11-28', '12-25'],
    2025: ['01-01', '01-09', '01-20', '02-17', '04-18', '05-26', '06-19', '07-04', '09-01', '11-27', '12-25'], // Jan 9: national day of mourning
    2026: ['01-01', '01-19', '02-16', '04-03', '05-25', '06-19', '07-03', '09-07', '11-26', '12-25'], // Jul 4 Saturday → Fri Jul 3
    2027: ['01-01', '01-18', '02-15', '03-26', '05-31', '06-18', '07-05', '09-06', '11-25', '12-24'],
  };
  for (const [y, days] of Object.entries(expected)) {
    assertEquals(weekdayHolidays(NYSE, Number(y)), days, `NYSE ${y}`);
    assertEquals(weekdayHolidays(NASDAQ, Number(y)), days, `XNAS ${y}`);
  }
  assertEquals(weekdayHolidays(NYSE, 2021).includes('06-18'), false); // Juneteenth only from 2022
});

Deno.test('CAL-02 LSE holidays match the published schedules (substitute days, 2020 VE Day, 2022 Jubilee + state funeral, 2023 coronation)', () => {
  const expected: Record<number, string[]> = {
    2020: ['01-01', '04-10', '04-13', '05-08', '05-25', '08-31', '12-25', '12-28'],
    2021: ['01-01', '04-02', '04-05', '05-03', '05-31', '08-30', '12-27', '12-28'],
    2022: ['01-03', '04-15', '04-18', '05-02', '06-02', '06-03', '08-29', '09-19', '12-26', '12-27'],
    2023: ['01-02', '04-07', '04-10', '05-01', '05-08', '05-29', '08-28', '12-25', '12-26'],
    2025: ['01-01', '04-18', '04-21', '05-05', '05-26', '08-25', '12-25', '12-26'],
  };
  for (const [y, days] of Object.entries(expected)) assertEquals(weekdayHolidays(LSE, Number(y)), days, `LSE ${y}`);
});

Deno.test('CAL-03 Easter computus (known dates)', () => {
  assertEquals([2019, 2024, 2025, 2026, 2030].map(easterSunday), ['2019-04-21', '2024-03-31', '2025-04-20', '2026-04-05', '2030-04-21']);
});

Deno.test('CAL-04 sessions are evaluated in the exchange timezone, across DST, with early closes', () => {
  const ny = (d: string) => sessionTimes(NYSE, d)!;
  assertEquals(new Date(ny('2026-01-12').openMs).toISOString(), '2026-01-12T14:30:00.000Z'); // EST
  assertEquals(new Date(ny('2026-03-09').openMs).toISOString(), '2026-03-09T13:30:00.000Z'); // EDT (DST began Mar 8)
  assertEquals(new Date(ny('2025-11-28').closeMs).toISOString(), '2025-11-28T18:00:00.000Z'); // 13:00 ET after Thanksgiving
  assertEquals(ny('2025-07-03').earlyClose, true);
  assertEquals(ny('2026-07-02').earlyClose, false); // Jul 3 2026 is the observed holiday, no early close
  const lon = sessionTimes(LSE, '2026-07-01')!;
  assertEquals([new Date(lon.openMs).toISOString(), new Date(lon.closeMs).toISOString()], ['2026-07-01T07:00:00.000Z', '2026-07-01T15:30:00.000Z']); // BST
  assertEquals(new Date(sessionTimes(LSE, '2025-12-24')!.closeMs).toISOString(), '2025-12-24T12:30:00.000Z');
  assertEquals(sessionTimes(NYSE, '2026-01-10'), null); // Saturday
});

Deno.test('CAL-05 unsupported MIC or out-of-range dates are UNKNOWN, never guessed', () => {
  assertEquals(calendarForMic('XTSE'), null);
  assertEquals(calendarForMic(undefined), null);
  assertEquals(calendarForMic('__proto__'), null);
  assertEquals(isTradingDay(NYSE, '2014-12-31'), null);
  assertEquals(isTradingDay(NYSE, '2031-01-02'), null);
  assertEquals(marketClock(NYSE, Date.UTC(2031, 5, 1)), null);
  assertEquals(marketClock(NYSE, NaN), null);
});

Deno.test('CAL-06 market clock: open/closed state and last completed session', () => {
  const c = (ms: number) => marketClock(NYSE, ms)!;
  assertEquals(c(Date.UTC(2026, 0, 12, 15)).state, 'OPEN'); // Mon 10:00 ET
  assertEquals(c(Date.UTC(2026, 0, 12, 13)).state, 'CLOSED'); // Mon 08:00 ET
  assertEquals(c(Date.UTC(2026, 0, 12, 15)).lastCompletedSession, '2026-01-09');
  assertEquals(c(Date.UTC(2026, 0, 12, 23)).lastCompletedSession, '2026-01-12'); // 18:00 ET = close + 2h grace
  assertEquals(c(Date.UTC(2026, 0, 12, 22)).lastCompletedSession, '2026-01-09'); // inside publication grace
  assertEquals(c(Date.UTC(2026, 0, 19, 16)).state, 'CLOSED'); // MLK Day
  assertEquals(c(Date.UTC(2026, 0, 19, 16)).lastCompletedSession, '2026-01-16');
});

// ---------------------------------------------------------------- calendar-aware freshness

function dailyBar(date: string, close = 100): PriceBar {
  return { t: Date.parse(`${date}T00:00:00Z`), open: close, high: close, low: close, close };
}
const fresh = (bars: PriceBar[], mic: string | undefined, nowMs: number, freq: 'DAILY' | 'INTRADAY_1M' = 'DAILY') =>
  assessSessionFreshness(bars, freq, mic, bars[bars.length - 1].t, nowMs);

Deno.test('SF-01 DAILY: weekend and holidays are not staleness; sessions behind drive the state', () => {
  const fri = [dailyBar('2026-01-15'), dailyBar('2026-01-16')];
  // Saturday, Sunday and the MLK Monday holiday: still 0 sessions behind.
  for (const now of [Date.UTC(2026, 0, 17, 12), Date.UTC(2026, 0, 18, 12), Date.UTC(2026, 0, 19, 23)]) {
    const r = fresh(fri, 'XNYS', now);
    assertEquals([r.freshness.state, r.context.sessionsBehind], ['FRESH', 0], new Date(now).toISOString());
  }
  // Tuesday after close+grace: one session (Tue) missing → DELAYED; Wednesday evening → STALE.
  assertEquals(fresh(fri, 'XNYS', Date.UTC(2026, 0, 20, 23)).freshness.state, 'DELAYED');
  assertEquals(fresh(fri, 'XNYS', Date.UTC(2026, 0, 21, 23)).freshness.state, 'STALE');
  // The calendar-naive policy would call a 4-day-old bar FRESH and a 5-day-old DELAYED regardless of sessions.
  assertEquals(fresh(fri, 'XTST', Date.UTC(2026, 0, 21, 23)).context.basis, 'CALENDAR_NAIVE');
});

Deno.test('SF-02 DAILY: missing sessions and non-session bars are counted, never filled', () => {
  const bars = [dailyBar('2026-01-12'), dailyBar('2026-01-14'), dailyBar('2026-01-17'), dailyBar('2026-01-20')];
  const r = fresh(bars, 'XNYS', Date.UTC(2026, 0, 20, 23));
  // Trading days 13, 15, 16 are missing (19 is MLK). The Saturday 17th bar is a non-session bar.
  assertEquals([r.context.missingSessions, r.context.nonSessionBars], [3, 1]);
});

Deno.test('SF-03 DAILY: a bar for today\'s unfinished session is FRESH but flagged partial; a future bar is UNKNOWN', () => {
  const today = [dailyBar('2026-01-09'), dailyBar('2026-01-12')];
  const r = fresh(today, 'XNYS', Date.UTC(2026, 0, 12, 16)); // Mon 11:00 ET, session running
  assertEquals([r.freshness.state, r.context.partialSessionBar], ['FRESH', true]);
  const future = fresh([dailyBar('2026-01-09'), dailyBar('2026-01-14')], 'XNYS', Date.UTC(2026, 0, 12, 16));
  assertEquals(future.freshness.state, 'UNKNOWN');
});

Deno.test('SF-04 INTRADAY: while the market is closed, age runs from the last close (Friday 15:59 bar is fresh all weekend)', () => {
  const lastMinute = { t: Date.UTC(2026, 0, 16, 20, 59), open: 1, high: 1, low: 1, close: 1 };
  const weekend = fresh([lastMinute], 'XNYS', Date.UTC(2026, 0, 18, 12), 'INTRADAY_1M');
  assertEquals([weekend.freshness.state, weekend.context.marketState], ['FRESH', 'CLOSED']);
  // During Tuesday's session (after the MLK Monday holiday) the same bar is stale.
  assertEquals(fresh([lastMinute], 'XNYS', Date.UTC(2026, 0, 20, 16), 'INTRADAY_1M').freshness.state, 'STALE');
  // Unknown venue: calendar-naive → 2 days old is STALE for 1-minute bars.
  assertEquals(fresh([lastMinute], undefined, Date.UTC(2026, 0, 18, 12), 'INTRADAY_1M').freshness.state, 'STALE');
});

Deno.test('SF-05 London calendar end to end (timezone + bank holiday)', () => {
  const bars = [dailyBar('2025-08-21'), dailyBar('2025-08-22')]; // Thu, Fri
  // Monday 25 Aug 2025 is the Summer bank holiday: Tuesday morning London is still 0 sessions behind.
  const r = fresh(bars, 'XLON', Date.UTC(2025, 7, 26, 7));
  assertEquals([r.freshness.state, r.context.calendar, r.context.timezone], ['FRESH', 'XLON', 'Europe/London']);
});

Deno.test('SF-06 long history starting before the supported range keeps calendar freshness (missing count unknown)', () => {
  const bars = [dailyBar('2010-01-04'), dailyBar('2026-01-16')];
  const r = fresh(bars, 'XNYS', Date.UTC(2026, 0, 17, 12));
  assertEquals([r.context.basis, r.freshness.state, r.context.missingSessions], ['MARKET_CALENDAR', 'FRESH', null]);
  assert(r.context.nonSessionBars === 0);
});

Deno.test('CAL-07 Codex CXA-03 rejected with evidence: NYSE Rule 7.2 — a Saturday New Year is NOT observed on Friday Dec 31', () => {
  // NYSE was open on Friday 2021-12-31 (New Year's Day 2022 fell on a Saturday
  // and was not observed); 2022-01-03 was a normal session. Pinned so the
  // rule cannot be "fixed" into a wrong closure.
  assertEquals(isTradingDay(NYSE, '2021-12-31'), true);
  assertEquals(isTradingDay(NYSE, '2022-01-03'), true);
  assertEquals(isTradingDay(NYSE, '2022-01-01'), false); // Saturday
  const bars = [dailyBar('2021-12-30'), dailyBar('2021-12-31')];
  const r = assessSessionFreshness(bars, 'DAILY', 'XNYS', bars[1].t, Date.UTC(2022, 0, 3, 12));
  assertEquals([r.freshness.state, r.context.sessionsBehind, r.context.missingSessions], ['FRESH', 0, 0]);
});

Deno.test('SF-07 DAILY bars stamped with a local evening time map to the exchange-local session (finding H-F)', () => {
  // Friday 2026-01-16 21:00 New York = 2026-01-17T02:00Z (Saturday in UTC).
  const bars: PriceBar[] = [
    { t: Date.parse('2026-01-15T21:00:00-05:00'), open: 1, high: 1, low: 1, close: 1 },
    { t: Date.parse('2026-01-16T21:00:00-05:00'), open: 1, high: 1, low: 1, close: 1 },
  ];
  const r = assessSessionFreshness(bars, 'DAILY', 'XNYS', bars[1].t, Date.UTC(2026, 0, 17, 12));
  assertEquals([r.freshness.state, r.context.sessionsBehind, r.context.nonSessionBars, r.context.missingSessions], ['FRESH', 0, 0, 0]);
  // Date-only labels keep their calendar date (unchanged behaviour).
  const labels = [dailyBar('2026-01-15'), dailyBar('2026-01-16')];
  assertEquals(assessSessionFreshness(labels, 'DAILY', 'XNYS', labels[1].t, Date.UTC(2026, 0, 17, 12)).context.nonSessionBars, 0);
});
