#!/usr/bin/env bash
# Migration content integrity (IV-IVE-AEF-RUNTIME-INTEGRATION-01, F-01).
#
# supabase/migration_manifest.tsv records, for EVERY file in
# supabase/migrations/, the sha256 of its canonical content and its status:
#   APPLIED_PRODUCTION  recorded in the production history (read-only
#                       preflight evidence) — its content is FROZEN;
#   LAB                 not applied anywhere outside disposable databases.
# Canonical content = the file's bytes with CRLF normalized to LF (so a
# Windows checkout and CI hash the same), nothing else.
#
#   --check (default)  fail closed on: missing/unreadable manifest, malformed
#                      or duplicate row, unknown status, a manifest row whose
#                      file is missing (deleted/renamed), a migration file
#                      without a row (unexpected/renamed), a digest mismatch
#                      (same name, changed content).
#   --write            add rows for new files and refresh LAB digests. It
#                      NEVER rewrites an APPLIED_PRODUCTION digest: changing
#                      an applied migration is refused (edit the manifest by
#                      hand, visibly, under an authorized mission).
#
# Env overrides (tests): MIGRATIONS_DIR, MANIFEST.
# Supabase's production history stores names and apply versions, not content
# digests: this manifest protects the REPOSITORY side; the deploy preflight's
# structural fingerprints cover the database side.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MIGRATIONS_DIR="${MIGRATIONS_DIR:-$ROOT/supabase/migrations}"
MANIFEST="${MANIFEST:-$ROOT/supabase/migration_manifest.tsv}"
MODE="${1:---check}"

fail() { echo "MIGRATION_MANIFEST: FAIL — $*" >&2; exit 1; }
digest() { tr -d '\r' < "$1" | sha256sum | cut -d' ' -f1; }

declare -A DIGEST=() STATUS=()
ORDER=()
if [[ -f "$MANIFEST" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    IFS=$'\t' read -r name sum status extra <<< "$line"
    [[ -n "${name:-}" && -n "${sum:-}" && -n "${status:-}" && -z "${extra:-}" ]] || fail "malformed row: $line"
    [[ "$name" =~ ^[0-9]{14}_[a-z0-9_]+\.sql$ ]] || fail "malformed migration name: $name"
    [[ "$sum" =~ ^[0-9a-f]{64}$ ]] || fail "malformed digest for $name"
    [[ "$status" == "APPLIED_PRODUCTION" || "$status" == "LAB" ]] || fail "unknown status '$status' for $name"
    [[ -z "${DIGEST[$name]+x}" ]] || fail "duplicate manifest entry: $name"
    DIGEST[$name]="$sum"; STATUS[$name]="$status"; ORDER+=("$name")
  done < "$MANIFEST"
elif [[ "$MODE" != "--write" ]]; then
  fail "manifest missing: $MANIFEST"
fi

FILES=()
for f in "$MIGRATIONS_DIR"/*.sql; do
  [[ -e "$f" ]] || continue
  FILES+=("$(basename "$f")")
done

if [[ "$MODE" == "--check" ]]; then
  [[ ${#ORDER[@]} -gt 0 ]] || fail "manifest is empty"
  for name in "${ORDER[@]}"; do
    [[ -f "$MIGRATIONS_DIR/$name" ]] || fail "manifest entry without file (deleted or renamed): $name"
  done
  for name in "${FILES[@]}"; do
    [[ -n "${DIGEST[$name]+x}" ]] || fail "migration not in manifest (unexpected or renamed): $name"
    actual="$(digest "$MIGRATIONS_DIR/$name")"
    [[ "$actual" == "${DIGEST[$name]}" ]] || fail "content changed for ${STATUS[$name]} migration $name (manifest ${DIGEST[$name]:0:12}…, file ${actual:0:12}…)"
  done
  echo "MIGRATION_MANIFEST: PASS — ${#FILES[@]} migrations, content verified"
  exit 0
fi

[[ "$MODE" == "--write" ]] || fail "unknown mode $MODE"
for name in "${ORDER[@]}"; do
  [[ -f "$MIGRATIONS_DIR/$name" ]] || fail "manifest entry without file (deleted or renamed): $name — refusing to drop it silently"
done
{
  echo "# Migration content manifest — generated by scripts/ci/migration_manifest.sh --write."
  echo "# name<TAB>sha256(canonical content, CRLF->LF)<TAB>APPLIED_PRODUCTION|LAB"
  for name in "${FILES[@]}"; do
    actual="$(digest "$MIGRATIONS_DIR/$name")"
    if [[ "${STATUS[$name]:-}" == "APPLIED_PRODUCTION" ]]; then
      [[ "$actual" == "${DIGEST[$name]}" ]] || fail "refusing to rewrite the digest of APPLIED_PRODUCTION migration $name"
      printf '%s\t%s\t%s\n' "$name" "$actual" "APPLIED_PRODUCTION"
    else
      printf '%s\t%s\t%s\n' "$name" "$actual" "${STATUS[$name]:-LAB}"
    fi
  done
} > "$MANIFEST.tmp"
mv "$MANIFEST.tmp" "$MANIFEST"
echo "MIGRATION_MANIFEST: WRITTEN — ${#FILES[@]} rows"
