-- IV-QUANT-DATA-PLANE-AND-API-02 — Quant watchlists (Quant Lab only; NOT applied to production).
--
-- First user-owned Quant persistence. Minimal relational model:
--   quant_watchlists       one row per watchlist, owned by a user, optional project
--   quant_watchlist_items  one row per canonical instrument in a watchlist
--
-- Security model (docs/quant/QUANT_WATCHLIST_MODEL.md):
--   * RLS on both tables; every policy is `user_id = auth.uid()`; items also
--     require the parent watchlist to belong to the same user.
--   * Module entitlement is ALSO enforced here (Codex CXA-01): module
--     'quant-watchlists' is INTERNAL (admin-only), so every policy requires
--     public.quant_watchlists_access_allowed() — true only for a caller whose
--     own server-managed role is admin (profiles.role, or subject_roles when
--     that table exists). Direct PostgREST access therefore cannot bypass the
--     Edge Function's entitlement gate. Promoting the module beyond INTERNAL
--     REQUIRES a new migration replacing this predicate; the Deno drift test
--     QB-16 fails CI if module_policy.ts and this predicate disagree.
--   * anon: no privileges at all. authenticated: SELECT/INSERT/DELETE, and
--     UPDATE of `name` ONLY (column privilege) — user_id/project_id/items
--     can never be rewritten, so a row cannot be moved to another user or
--     project after creation. Items are immutable (no UPDATE privilege).
--   * project_id, when set, must reference a project owned by the caller
--     (checked in the INSERT policy, same `auth.uid() = user_id` rule as
--     public.projects' own RLS). Deleting the project detaches the watchlist
--     (ON DELETE SET NULL) instead of silently deleting user data.
--   * Identity is the Foundation's canonical instrument identity (asset
--     class + MIC + symbol + currency), never a bare ticker; instrument_key
--     is generated by the database, so it cannot be forged.
--   * Limits enforced in the database too (200 items per watchlist, 50
--     watchlists per user), race-safe via row/advisory locks.
-- Idempotent: safe to re-apply.

CREATE TABLE IF NOT EXISTS public.quant_watchlists (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE CASCADE,
  project_id  uuid NULL REFERENCES public.projects (id) ON DELETE SET NULL,
  name        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT quant_watchlists_name_chk CHECK (char_length(btrim(name)) BETWEEN 1 AND 80 AND name = btrim(name))
);

CREATE TABLE IF NOT EXISTS public.quant_watchlist_items (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id   uuid NOT NULL REFERENCES public.quant_watchlists (id) ON DELETE CASCADE,
  user_id        uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE CASCADE,
  asset_class    text NOT NULL,
  symbol         text NOT NULL,
  exchange_mic   text NULL,
  currency       text NOT NULL,
  isin           text NULL,
  figi           text NULL,
  instrument_key text GENERATED ALWAYS AS (asset_class || ':' || coalesce(exchange_mic, 'UNSPECIFIED') || ':' || symbol || ':' || currency) STORED,
  created_at     timestamptz NOT NULL DEFAULT now(),
  -- Foundation-supported analytic classes only (widened by a future migration with the engine).
  CONSTRAINT quant_watchlist_items_class_chk CHECK (asset_class IN ('EQUITY', 'ETF', 'INDEX')),
  CONSTRAINT quant_watchlist_items_symbol_chk CHECK (symbol ~ '^[A-Z0-9][A-Z0-9.=/-]{0,31}$'),
  CONSTRAINT quant_watchlist_items_mic_chk CHECK (exchange_mic IS NULL OR exchange_mic ~ '^[A-Z0-9]{4}$'),
  CONSTRAINT quant_watchlist_items_ccy_chk CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT quant_watchlist_items_isin_chk CHECK (isin IS NULL OR isin ~ '^[A-Z]{2}[A-Z0-9]{9}[0-9]$'),
  CONSTRAINT quant_watchlist_items_figi_chk CHECK (figi IS NULL OR figi ~ '^[B-DF-HJ-NP-TV-Z0-9]{2}G[B-DF-HJ-NP-TV-Z0-9]{8}[0-9]$'),
  CONSTRAINT quant_watchlist_items_unique_instrument UNIQUE (watchlist_id, instrument_key)
);

CREATE INDEX IF NOT EXISTS quant_watchlists_user_idx ON public.quant_watchlists (user_id);
CREATE INDEX IF NOT EXISTS quant_watchlists_project_idx ON public.quant_watchlists (project_id) WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS quant_watchlist_items_watchlist_idx ON public.quant_watchlist_items (watchlist_id);
CREATE INDEX IF NOT EXISTS quant_watchlist_items_user_idx ON public.quant_watchlist_items (user_id);

-- ── limits + updated_at (SECURITY INVOKER, pinned search_path) ──────────
CREATE OR REPLACE FUNCTION public.quant_watchlists_before_write()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Serialize concurrent creates by the same user so the cap cannot be raced.
    PERFORM pg_advisory_xact_lock(hashtextextended('quant_watchlists:' || NEW.user_id::text, 0));
    IF (SELECT count(*) FROM public.quant_watchlists w WHERE w.user_id = NEW.user_id) >= 50 THEN
      RAISE EXCEPTION 'QUANT_WATCHLIST_LIMIT' USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS quant_watchlists_before_write ON public.quant_watchlists;
CREATE TRIGGER quant_watchlists_before_write BEFORE INSERT OR UPDATE ON public.quant_watchlists
  FOR EACH ROW EXECUTE FUNCTION public.quant_watchlists_before_write();

CREATE OR REPLACE FUNCTION public.quant_watchlist_items_before_insert()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
BEGIN
  -- Lock the parent row: concurrent inserts into one watchlist are serialized.
  PERFORM 1 FROM public.quant_watchlists w WHERE w.id = NEW.watchlist_id FOR UPDATE;
  IF (SELECT count(*) FROM public.quant_watchlist_items i WHERE i.watchlist_id = NEW.watchlist_id) >= 200 THEN
    RAISE EXCEPTION 'QUANT_WATCHLIST_ITEM_LIMIT' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS quant_watchlist_items_before_insert ON public.quant_watchlist_items;
CREATE TRIGGER quant_watchlist_items_before_insert BEFORE INSERT ON public.quant_watchlist_items
  FOR EACH ROW EXECUTE FUNCTION public.quant_watchlist_items_before_insert();

-- ── module entitlement predicate (INTERNAL = admin-only) ───────────────────
-- SECURITY INVOKER: reads only the caller's OWN profile / role rows under
-- their existing RLS; grants nothing. Fails closed (NULL uid → false).
CREATE OR REPLACE FUNCTION public.quant_watchlists_access_allowed()
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE
  uid uuid := auth.uid();
  allowed boolean := false;
BEGIN
  IF uid IS NULL THEN
    RETURN false;
  END IF;
  SELECT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = uid AND p.role = 'admin') INTO allowed;
  IF NOT allowed AND to_regclass('public.subject_roles') IS NOT NULL THEN
    EXECUTE 'SELECT EXISTS (SELECT 1 FROM public.subject_roles r WHERE r.subject_type = ''user'' AND r.subject_id = $1 AND r.role = ''admin'')'
      INTO allowed USING uid;
  END IF;
  RETURN coalesce(allowed, false);
END $$;

-- ── RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE public.quant_watchlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quant_watchlist_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS quant_watchlists_select_own ON public.quant_watchlists;
CREATE POLICY quant_watchlists_select_own ON public.quant_watchlists
  FOR SELECT TO authenticated USING (user_id = auth.uid() AND public.quant_watchlists_access_allowed());

DROP POLICY IF EXISTS quant_watchlists_insert_own ON public.quant_watchlists;
CREATE POLICY quant_watchlists_insert_own ON public.quant_watchlists
  FOR INSERT TO authenticated WITH CHECK (
    user_id = auth.uid()
    AND public.quant_watchlists_access_allowed()
    AND (project_id IS NULL OR EXISTS (
      SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()
    ))
  );

DROP POLICY IF EXISTS quant_watchlists_update_own ON public.quant_watchlists;
CREATE POLICY quant_watchlists_update_own ON public.quant_watchlists
  FOR UPDATE TO authenticated USING (user_id = auth.uid() AND public.quant_watchlists_access_allowed())
  WITH CHECK (user_id = auth.uid() AND public.quant_watchlists_access_allowed());

DROP POLICY IF EXISTS quant_watchlists_delete_own ON public.quant_watchlists;
CREATE POLICY quant_watchlists_delete_own ON public.quant_watchlists
  FOR DELETE TO authenticated USING (user_id = auth.uid() AND public.quant_watchlists_access_allowed());

DROP POLICY IF EXISTS quant_watchlist_items_select_own ON public.quant_watchlist_items;
CREATE POLICY quant_watchlist_items_select_own ON public.quant_watchlist_items
  FOR SELECT TO authenticated USING (user_id = auth.uid() AND public.quant_watchlists_access_allowed());

DROP POLICY IF EXISTS quant_watchlist_items_insert_own ON public.quant_watchlist_items;
CREATE POLICY quant_watchlist_items_insert_own ON public.quant_watchlist_items
  FOR INSERT TO authenticated WITH CHECK (
    user_id = auth.uid()
    AND public.quant_watchlists_access_allowed()
    AND EXISTS (SELECT 1 FROM public.quant_watchlists w WHERE w.id = watchlist_id AND w.user_id = auth.uid())
  );

DROP POLICY IF EXISTS quant_watchlist_items_delete_own ON public.quant_watchlist_items;
CREATE POLICY quant_watchlist_items_delete_own ON public.quant_watchlist_items
  FOR DELETE TO authenticated USING (user_id = auth.uid() AND public.quant_watchlists_access_allowed());

-- ── privileges (explicit; override Supabase default grants) ──────────────
REVOKE ALL ON public.quant_watchlists FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.quant_watchlist_items FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.quant_watchlists TO authenticated;
GRANT UPDATE (name) ON public.quant_watchlists TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.quant_watchlist_items TO authenticated;
GRANT ALL ON public.quant_watchlists, public.quant_watchlist_items TO service_role;

REVOKE ALL ON FUNCTION public.quant_watchlists_before_write() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.quant_watchlists_access_allowed() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.quant_watchlists_access_allowed() TO authenticated;
REVOKE ALL ON FUNCTION public.quant_watchlist_items_before_insert() FROM PUBLIC, anon, authenticated;
